<?php if ($this->isEnabled()): ?>
    <script data-role='loyaltylion' data-bind="scope: 'lionCustomer'">
!function(n,o){function t(o){var t=n.getElementsByTagName("script")[0],i=n.createElement("script");i.src=o,i.crossOrigin="",t.parentNode.insertBefore(i,t)}if(!o.isLoyaltyLion){window.loyaltylion=o,void 0===window.lion&&(window.lion=o),o.version=2,o.isLoyaltyLion=!0;var i=new Date;t("https://<?php echo $this->getLoaderUrl() ?>?t="+i.getFullYear()+i.getMonth()+i.getDate());var e=!1;o.init=function(n){if(e)throw new Error("Cannot call lion.init more than once");e=!0;var i=o._token=n.token;if(!i)throw new Error("Token must be supplied to lion.init");for(var r=[],a="_push configure bootstrap shutdown on removeListener".split(" "),l=0;l<a.length;l+=1)!function(n,o){n[o]=function(){r.push([o,Array.prototype.slice.call(arguments,0)])}}(o,a[l]);t("https://<?php echo $this->getSdkHost() ?>/sdk/start/"+i+".js"),o._initData=n,o._buffer=r}}}(document,window.loyaltylion||[]);
lion.init({ token: "<?php echo $this->getToken() ?>" });
    </script>
    <script type="text/x-magento-init">
    {"[data-role='loyaltylion']": {"Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>}}
    </script>
<?php endif ?>
