name: Lint

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
        env:
          COMPOSER_AUTH: ${{secrets.MAGENTO_MARKETPLACE_AUTH}}

      - name: Run linters
        run: ./vendor/bin/phpcs -ns .
